name = "about-daangn-com-production"
compatibility_date = "2024-04-03"
compatibility_flags = ["nodejs_compat"]
# upload_source_maps = true

pages_build_output_dir = "public"

# [secrets]
# PUBLIC_TAG=""

[[r2_buckets]]
binding = "CONTENT_BUCKET"
bucket_name = "about-daangn-com-production"
