name = 'greenhouse-proxy-worker'
main = 'src/worker.ts'
compatibility_date = '2022-10-12'
compatibility_flags = [
  'url_standard',
]
usage_model = 'unbound'
workers_dev = true

[vars]
TURNSTILE_ENABLED = true
