name = 'mbti-test'
type = 'javascript'
account_id = 'aad5c82543cd1f267b89737d0f56405e'
usage_model = ''
zone_id = ''
route = ''
workers_dev = true

kv_namespaces = [
  { binding = "MBTI_TEST", id = "6e6490568315477db7d3a7d24b071429", preview_id = "90e6c77d9b664a7c9418247b72f55c23" }
]

[build]
command = 'yarn esbuild src-worker/index.ts --bundle --outfile=dist/worker.js --format=esm'

[build.upload]
format = 'service-worker'
