name = "websites-integration"
pages_build_output_dir = "./public"
compatibility_date = "2025-12-15"
compatibility_flags = []

[observability]
enabled = true

[[r2_buckets]]
binding = "ARTIFACTS"
bucket_name = "websites-artifacts"

[[durable_objects.bindings]]
name = "DEPLOYMENT"
class_name = "Deployment"
script_name = "websites-integration"
