name = "websites-integration"
compatibility_date = "2025-12-15"
main = "_worker.js"
compatibility_flags = []

[observability]
enabled = true

[[durable_objects.bindings]]
name = "DEPLOYMENT"
class_name = "Deployment"

[[migrations]]
tag = "v1"
new_classes = ["Deployment"]
