name: Deploy about.daangn.com

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/deploy-about-daangn-com.yml
      - about.daangn.com/**
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Setup Rclone
        uses: cometkim/rclone-actions/setup-rclone@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Rclone
        run: |
          mkdir -p ~/.config/rclone
          {
            echo "[karrot]"
            echo "type = s3"
            echo "provider = Cloudflare"
            echo "access_key_id = ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}"
            echo "secret_access_key = ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}"
            echo "endpoint = https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com"
            echo "acl = private"
          } > ~/.config/rclone/rclone.conf
        shell: bash

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Get date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Restore content snapshot
        id: content-snapshot
        # Uses actions/cache instead of actions/upload-artifacts
        #
        # The implementation quality of actions/cache is superior to that of upload-artifacts/download-artifacts.
        # However, there are complex constraints.
        # See https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy
        #
        # The current site artifact is about 500MB due to zstd compression.
        #
        # Choose appropriate key stretagy to reduce cache thrashing and maximize hits.
        uses: actions/cache/restore@v4
        with:
          enableCrossOsArchive: true
          path: |
            about.daangn.com/public
          key: public-${{ steps.get-date.outputs.date }}
          restore-keys: public

      - name: Restore build cache
        id: build-cache
        uses: actions/cache/restore@v4
        with:
          path: |
            about.daangn.com/.cache
          key: build-cache-gatsby-v5-${{ runner.os }}

      - name: Build about.daangn.com
        run: yarn workspace about.daangn.com build

      - name: Save build cache
        uses: actions/cache/save@v4
        with:
          path: |
            about.daangn.com/.cache
          key: build-cache-gatsby-v5-${{ runner.os }}

      - name: Save content snapshot
        uses: actions/cache/save@v4
        with:
          enableCrossOsArchive: true
          path: |
            about.daangn.com/public
          key: public-${{ steps.get-date.outputs.date }}

      - name: Save content snapshot (backup)
        if: steps.content-snapshot.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          enableCrossOsArchive: true
          path: |
            about.daangn.com/public
          key: public

      - name: Upload artifacts (immutable first)
        run: |
          rclone sync \
            --quiet \
            --checksum \
            --fast-list \
            --transfers 8 \
            --checkers 16 \
            --buffer-size 32M \
            --stats 10 \
            --immutable about.daangn.com/public/static karrot:websites-about-daangn-com/static

      - name: Upload artifacts (all)
        run: |
          rclone sync \
            --quiet \
            --checksum \
            --fast-list \
            --transfers 8 \
            --checkers 16 \
            --buffer-size 32M \
            --stats 10 \
            about.daangn.com/public karrot:websites-about-daangn-com
