name: Deploy about-daangn-com-production

on:
  workflow_dispatch:
  push:
    paths:
      - _workers/about-daangn-com-production/**
      - .github/workflows/deploy-about-daangn-com-production.yml
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Get the Wrangler version
        id: wrangler-version
        run: |
          yarn workspace about-daangn-com-production wrangler --version |\
          cut -f 2 | sed 's/^/WRANGLER_VERSION=/' >> "$GITHUB_OUTPUT"

      - name: Deploy Pages
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: _workers/about-daangn-com-production
          packageManager: yarn
          wranglerVersion: ${{ steps.wrangler-version.outputs.WRANGLER_VERSION }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
