name: mbti.daangn.com production build

on:
  schedule:
    - cron: "0 0 1 * * *"
  push:
    branches:
      - main
    paths:
      - "mbti.daangn.com/**"
      - ".github/workflows/mbti.daangn.com-production.yml"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.ORG_GITHUB_READ_TOKEN }}
      GATSBY_CLOUDFRONT_DOMAIN: https://d2gbdddbstq0dk.cloudfront.net/prod

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-${GITHUB_REF##*/}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-master-yarn-${{ hashFiles('yarn.lock') }}
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: |
          yarn
      - name: Build app
        run: |
          yarn workspace mbti.daangn.com build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ORG_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ORG_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: S3 upload
        run: |
          aws s3 sync ./mbti.daangn.com/tmp/* s3://mbti.daangn.com/prod/
      - name: CloudFront Invalidate
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.MBTI_CF_DISTRIBUTION_ID }} \
          --paths /prod/*
