name: Build (& Deploy) us.karrotmarket.com

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/us_karrotmarket_com-*'
      - us.karrotmarket.com
      - yarn.lock
    branches:
      - main
  push:
    paths:
      - '.github/workflows/us_karrotmarket_com-*'
      - us.karrotmarket.com
      - yarn.lock
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build (& Deploy)
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      
      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn

      - name: Install Dependencies
        run: yarn install --immutable

      - name: Restore Gatsby Cache
        uses: actions/cache@v3
        with:
          path: |
            us.karrotmarket.com/.cache
            us.karrotmarket.com/public
          key: ${{ runner.os }}-gatsby-build-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: Build us.karrotmarket.com
        run: |
          yarn workspace us.karrotmarket.com build --log-pages
        env:
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
          HOT_ARTICLE_API_SPECIAL_KEY: ${{ secrets.HOT_ARTICLE_API_SPECIAL_KEY }}
          ASSETS_PREFIX: https://assets.us.karrotmarket.com
          PREFIX_PATHS: true
          NODE_ENV: production
          CI: true

      - name: Deploy us.karrotmarket.com
        if: github.event_name != 'pull_request'
        uses: jonelantha/gatsby-s3-action@v2
        with:
          dest-s3-bucket: us.karrotmarket.com
          cloudfront-id-to-invalidate: E35E31R7XDWVCM
          public-source-path: us.karrotmarket.com/public
